In [1]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

USERNAME = os.getenv("DB_USER")
PASSWORD = os.getenv("DB_PASSWORD")
HOST = os.getenv("DB_HOST")
PORT = os.getenv("DB_PORT")
DATABASE = os.getenv("DB_NAME")

DATABASE_URL = (
    f"postgresql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)

engine = create_engine(DATABASE_URL)

print("✅ PostgreSQL Connected Successfully!")

✅ PostgreSQL Connected Successfully!

In [2]:
df = pd.read_csv(
    "../data/raw/fmcg_sales_3years_1M_rows.csv"
)

print(df.shape)

(1100000, 33)

In [3]:
df.head()

,date,year,month,day,weekofyear,weekday,is_weekend,is_holiday,temperature,rain_mm,...,discount_pct,promo_flag,gross_sales,net_sales,stock_on_hand,stock_out_flag,lead_time_days,supplier_id,purchase_cost,margin_pct
0,2021-01-01,2021,1,1,53,4,0,1,8.44,1.24,...,0.1,1,167.84,151.06,248,0,11,S008,7.53,0.182
1,2021-01-02,2021,1,2,53,5,1,0,12.61,1.12,...,0.0,0,125.88,125.88,238,0,6,S057,5.19,0.505
2,2021-01-03,2021,1,3,53,6,1,0,12.02,2.69,...,0.3,1,398.62,279.03,238,0,6,S017,5.59,0.168
3,2021-01-04,2021,1,4,1,0,0,0,7.76,4.65,...,0.0,0,83.92,83.92,216,0,7,S012,7.81,0.255
4,2021-01-05,2021,1,5,1,1,0,0,11.16,1.77,...,0.2,1,178.33,142.66,372,0,8,S038,7.62,0.073

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100000 entries, 0 to 1099999
Data columns (total 33 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   date            1100000 non-null  object
 1   year            1100000 non-null  int64
 2   month           1100000 non-null  int64
 3   day             1100000 non-null  int64
 4   weekofyear      1100000 non-null  int64
 5   weekday         1100000 non-null  int64
 6   is_weekend      1100000 non-null  int64
 7   is_holiday      1100000 non-null  int64
 8   temperature     1100000 non-null  float64
 9   rain_mm         1100000 non-null  float64
 10  store_id        1100000 non-null  object
 11  country         1100000 non-null  object
 12  city            1100000 non-null  object
 13  channel         1100000 non-null  object
 14  latitude        1100000 non-null  float64
 15  longitude       1100000 non-null  float64
 16  sku_id          1100000 non-null  object
 17  sku_name        1100000 non-null  object
 18  category        1100000 non-null  object
 19  subcategory     1100000 non-null  object
 20  brand           1100000 non-null  object
 21  units_sold      1100000 non-null  int64
 22  list_price      1100000 non-null  float64
 23  discount_pct    1100000 non-null  float64
 24  promo_flag      1100000 non-null  int64
 25  gross_sales     1100000 non-null  float64
 26  net_sales       1100000 non-null  float64
 27  stock_on_hand   1100000 non-null  int64
 28  stock_out_flag  1100000 non-null  int64
 29  lead_time_days  1100000 non-null  int64
 30  supplier_id     1100000 non-null  object
 31  purchase_cost   1100000 non-null  float64
 32  margin_pct      1100000 non-null  float64
dtypes: float64(10), int64(12), object(11)
memory usage: 276.9+ MB

In [5]:
df.describe()

,year,month,day,weekofyear,weekday,is_weekend,is_holiday,temperature,rain_mm,latitude,...,list_price,discount_pct,promo_flag,gross_sales,net_sales,stock_on_hand,stock_out_flag,lead_time_days,purchase_cost,margin_pct
count,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,...,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06,1.100000e+06
mean,2.022000e+03,6.525613e+00,1.572044e+01,2.657081e+01,3.005479e+00,2.867582e-01,1.369818e-02,1.281501e+01,2.904106e+00,4.630581e+01,...,7.712100e+00,1.496241e-02,8.023364e-02,4.406806e+02,4.299513e+02,2.994757e+02,3.010364e-02,6.500404e+00,4.625546e+00,3.852405e-01
std,8.164700e-01,3.447760e+00,8.796262e+00,1.505126e+01,2.000451e+00,4.522478e-01,1.162349e-01,3.371587e+00,2.098997e+00,4.602927e+00,...,4.253023e+00,5.477955e-02,2.716547e-01,4.418005e+02,4.224992e+02,8.007292e+01,1.708726e-01,2.014065e+00,2.662604e+00,1.024581e-01
min,2.021000e+03,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.800000e+00,0.000000e+00,4.041706e+01,...,1.080000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,4.900000e-01,-5.000000e-02
25%,2.021000e+03,4.000000e+00,8.000000e+00,1.400000e+01,1.000000e+00,0.000000e+00,0.000000e+00,1.061000e+01,1.220000e+00,4.190833e+01,...,4.200000e+00,0.000000e+00,0.000000e+00,1.324400e+02,1.307675e+02,2.450000e+02,0.000000e+00,5.000000e+00,2.400000e+00,3.120000e-01
50%,2.022000e+03,7.000000e+00,1.600000e+01,2.700000e+01,3.000000e+00,0.000000e+00,0.000000e+00,1.284000e+01,2.570000e+00,4.546266e+01,...,7.380000e+00,0.000000e+00,0.000000e+00,2.828800e+02,2.778600e+02,3.000000e+02,0.000000e+00,6.000000e+00,4.350000e+00,3.890000e-01
75%,2.023000e+03,1.000000e+01,2.300000e+01,4.000000e+01,5.000000e+00,1.000000e+00,0.000000e+00,1.500000e+01,4.150000e+00,5.225287e+01,...,1.165000e+01,0.000000e+00,0.000000e+00,6.052800e+02,5.934600e+02,3.540000e+02,0.000000e+00,8.000000e+00,6.770000e+00,4.690000e-01
max,2.023000e+03,1.200000e+01,3.100000e+01,5.300000e+01,6.000000e+00,1.000000e+00,1.000000e+00,2.283000e+01,1.158000e+01,5.252586e+01,...,1.480000e+01,3.000000e-01,1.000000e+00,6.593900e+03,5.144940e+03,6.980000e+02,1.000000e+00,1.700000e+01,1.110000e+01,5.500000e-01

In [6]:
df.to_sql(
    name="fmcg_sales",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data Loaded Successfully")

Data Loaded Successfully

In [10]:
query = """
SELECT COUNT(*) AS total_rows
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   total_rows
0     1100000

In [7]:
query = """
SELECT COUNT(*)
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

     count
0  1100000

In [11]:
query = """

SELECT COUNT(*)

FROM information_schema.columns

WHERE table_name='fmcg_sales';

"""

pd.read_sql(query, engine)

   count
0     33

In [12]:
query = """

SELECT *

FROM fmcg_sales

LIMIT 10;

"""

pd.read_sql(query, engine)

,date,year,month,day,weekofyear,weekday,is_weekend,is_holiday,temperature,rain_mm,...,discount_pct,promo_flag,gross_sales,net_sales,stock_on_hand,stock_out_flag,lead_time_days,supplier_id,purchase_cost,margin_pct
0,2021-08-14,2021,8,14,32,5,1,0,15.43,0.16,...,0.0,0,285.95,285.95,307,0,7,S003,4.08,0.501
1,2021-08-15,2021,8,15,32,6,1,1,7.03,3.08,...,0.0,0,318.63,318.63,245,0,5,S012,3.92,0.520
2,2021-08-16,2021,8,16,33,0,0,0,8.88,1.43,...,0.0,0,310.46,310.46,232,0,5,S003,5.20,0.363
3,2021-08-17,2021,8,17,33,1,0,0,11.01,2.33,...,0.0,0,220.59,220.59,251,0,6,S027,5.69,0.303
4,2021-08-18,2021,8,18,33,2,0,0,13.13,1.90,...,0.0,0,179.74,179.74,403,0,9,S004,4.66,0.429
5,2021-08-19,2021,8,19,33,3,0,0,14.77,1.38,...,0.0,0,228.76,228.76,335,0,7,S022,3.92,0.520
6,2021-08-20,2021,8,20,33,4,0,0,11.20,1.61,...,0.0,0,285.95,285.95,392,0,5,S010,5.28,0.354
7,2021-08-21,2021,8,21,33,5,1,0,14.10,3.65,...,0.0,0,302.29,302.29,190,0,5,S048,3.91,0.521
8,2021-08-22,2021,8,22,33,6,1,0,11.43,0.35,...,0.0,0,498.37,498.37,271,0,5,S052,4.02,0.509
9,2021-08-23,2021,8,23,34,0,0,0,12.02,2.28,...,0.0,0,261.44,261.44,263,0,4,S046,3.91,0.522

In [13]:
query = """
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_name='fmcg_sales';
"""

schema = pd.read_sql(query, engine)

schema

       column_name         data_type
0       list_price  double precision
1     discount_pct  double precision
2       promo_flag            bigint
3      gross_sales  double precision
4        net_sales  double precision
5    stock_on_hand            bigint
6   stock_out_flag            bigint
7   lead_time_days            bigint
8             year            bigint
9    purchase_cost  double precision
10      margin_pct  double precision
11           month            bigint
12             day            bigint
13      weekofyear            bigint
14        latitude  double precision
15       longitude  double precision
16         weekday            bigint
17      is_weekend            bigint
18      is_holiday            bigint
19     temperature  double precision
20         rain_mm  double precision
21      units_sold            bigint
22          sku_id              text
23        store_id              text
24         country              text
25            city              text
26         channel              text
27            date              text
28        sku_name              text
29        category              text
30     subcategory              text
31           brand              text
32     supplier_id              text

In [16]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';
"""

tables = pd.read_sql(query, engine)

tables

   table_name
0  fmcg_sales

In [15]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

tables = pd.read_sql(query, engine)

tables

   table_name
0  fmcg_sales

In [14]:
query = """
SELECT COUNT(*) AS total_records
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   total_records
0        1100000

In [17]:
query = """
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_name='fmcg_sales'
ORDER BY ordinal_position;
"""

pd.read_sql(query, engine)

       column_name         data_type
0             date              text
1             year            bigint
2            month            bigint
3              day            bigint
4       weekofyear            bigint
5          weekday            bigint
6       is_weekend            bigint
7       is_holiday            bigint
8      temperature  double precision
9          rain_mm  double precision
10        store_id              text
11         country              text
12            city              text
13         channel              text
14        latitude  double precision
15       longitude  double precision
16          sku_id              text
17        sku_name              text
18        category              text
19     subcategory              text
20           brand              text
21      units_sold            bigint
22      list_price  double precision
23    discount_pct  double precision
24      promo_flag            bigint
25     gross_sales  double precision
26       net_sales  double precision
27   stock_on_hand            bigint
28  stock_out_flag            bigint
29  lead_time_days            bigint
30     supplier_id              text
31   purchase_cost  double precision
32      margin_pct  double precision