# SQL Analysis

## Objectives

This notebook demonstrates SQL querying skills by:

- Retrieving data
- Validating data quality
- Aggregating sales
- Performing business analysis
- Using window functions
- Preparing insights for machine learning

In [1]:
# ==========================================
# Import Libraries
# ==========================================

import os
import pandas as pd

from dotenv import load_dotenv
from sqlalchemy import create_engine

# ==========================================
# Load Environment Variables
# ==========================================

load_dotenv()

# ==========================================
# PostgreSQL Connection Details
# ==========================================

USERNAME = os.getenv("DB_USER")
PASSWORD = os.getenv("DB_PASSWORD")
HOST = os.getenv("DB_HOST")
PORT = os.getenv("DB_PORT")
DATABASE = os.getenv("DB_NAME")

DATABASE_URL = (
    f"postgresql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)

engine = create_engine(DATABASE_URL)

print("✅ Database Connected Successfully!")

✅ Database Connected Successfully!

In [2]:
query = """
SELECT current_database();
"""

pd.read_sql(query, engine)

  current_database
0          fmcg_db

In [2]:
print("User:", USERNAME)
print("Host:", HOST)
print("Database:", DATABASE)

User: postgres
Host: localhost
Database: fmcg_db

In [3]:
try:
    with engine.connect() as connection:
        print("✅ PostgreSQL connection established!")

except Exception as e:
    print("❌ Connection failed!")
    print(e)

✅ PostgreSQL connection established!

In [3]:
query = """
SELECT COUNT(*) AS total_rows
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   total_rows
0     1100000

In [4]:
query = """
SELECT COUNT(*) AS total_rows
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   total_rows
0     1100000

In [5]:
query = """
SELECT COUNT(*) AS total_columns
FROM information_schema.columns
WHERE table_name='fmcg_sales';
"""

pd.read_sql(query, engine)

   total_columns
0             33

In [6]:
query = """
SELECT
    ordinal_position,
    column_name,
    data_type
FROM information_schema.columns
WHERE table_name='fmcg_sales'
ORDER BY ordinal_position;
"""

schema = pd.read_sql(query, engine)

schema

    ordinal_position     column_name         data_type
0                  1            date              text
1                  2            year            bigint
2                  3           month            bigint
3                  4             day            bigint
4                  5      weekofyear            bigint
5                  6         weekday            bigint
6                  7      is_weekend            bigint
7                  8      is_holiday            bigint
8                  9     temperature  double precision
9                 10         rain_mm  double precision
10                11        store_id              text
11                12         country              text
12                13            city              text
13                14         channel              text
14                15        latitude  double precision
15                16       longitude  double precision
16                17          sku_id              text
17                18        sku_name              text
18                19        category              text
19                20     subcategory              text
20                21           brand              text
21                22      units_sold            bigint
22                23      list_price  double precision
23                24    discount_pct  double precision
24                25      promo_flag            bigint
25                26     gross_sales  double precision
26                27       net_sales  double precision
27                28   stock_on_hand            bigint
28                29  stock_out_flag            bigint
29                30  lead_time_days            bigint
30                31     supplier_id              text
31                32   purchase_cost  double precision
32                33      margin_pct  double precision

In [7]:
query = """
SELECT COUNT(DISTINCT country) AS countries
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   countries
0          7

In [8]:
query = """
SELECT COUNT(DISTINCT city) AS cities
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   cities
0       9

In [9]:
query = """
SELECT COUNT(DISTINCT channel) AS channels
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   channels
0         4

In [10]:
query = """
SELECT COUNT(DISTINCT sku_id) AS skus
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   skus
0   102

In [12]:
query = """
SELECT
    MIN(date) AS first_date,
    MAX(date) AS last_date
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   first_date   last_date
0  2021-01-01  2023-12-31

In [13]:
query = """
SELECT
    country,
    SUM(net_sales) AS total_revenue
FROM fmcg_sales
GROUP BY country
ORDER BY total_revenue DESC;
"""

country_sales = pd.read_sql(query, engine)

country_sales

       country  total_revenue
0        Italy   1.371931e+08
1        Spain   1.067048e+08
2      Germany   8.852556e+07
3      Austria   4.302003e+07
4       France   4.260161e+07
5       Poland   4.238526e+07
6  Netherlands   1.251615e+07

In [14]:
query = """
SELECT
    channel,
    SUM(net_sales) AS revenue
FROM fmcg_sales
GROUP BY channel
ORDER BY revenue DESC;
"""

channel_sales = pd.read_sql(query, engine)

channel_sales

       channel       revenue
0  Hypermarket  2.587381e+08
1   E-commerce  1.127345e+08
2  Supermarket  8.895766e+07
3  Convenience  1.251615e+07

In [15]:
query = """
SELECT
    sku_name,
    SUM(net_sales) AS revenue
FROM fmcg_sales
GROUP BY sku_name
ORDER BY revenue DESC
LIMIT 20;
"""

top_products = pd.read_sql(query, engine)

top_products

             sku_name      revenue
0        BrandF Water  17032424.64
1        BrandC Chips  16000295.02
2        BrandB Chips  13025419.73
3   BrandC Toothpaste  12968809.43
4         BrandB Soap  12496995.90
5   BrandD Toothpaste  12351150.68
6       BrandD Cheese  12326994.00
7       BrandA Cheese  11967260.40
8        BrandD Chips  11749108.59
9   BrandA Toothpaste  11594508.71
10    BrandE Biscuits  10887379.87
11    BrandB Biscuits  10826032.60
12        BrandD Milk  10664140.20
13        BrandA Soda  10515682.83
14        BrandC Milk  10224239.22
15        BrandE Soda   9685683.36
16        BrandF Milk   9466848.00
17        BrandF Nuts   8917389.91
18        BrandB Soda   8625588.75
19        BrandC Nuts   8089038.53

In [21]:
query = """
SELECT
    sku_name,
    ROUND(AVG(list_price), 2) AS average_price
FROM fmcg_sales
GROUP BY sku_name
ORDER BY average_price DESC;
"""

avg_price = pd.read_sql(query, engine)

avg_price.head(10)

ProgrammingError: (psycopg2.errors.UndefinedFunction) function round(double precision, integer) does not exist
LINE 4:     ROUND(AVG(list_price), 2) AS average_price
            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL:
SELECT
    sku_name,
    ROUND(AVG(list_price), 2) AS average_price
FROM fmcg_sales
GROUP BY sku_name
ORDER BY average_price DESC;
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [17]:
query = """
SELECT *
FROM fmcg_sales
LIMIT 5;
"""

sample = pd.read_sql(query, engine)

sample

,date,year,month,day,weekofyear,weekday,is_weekend,is_holiday,temperature,rain_mm,...,discount_pct,promo_flag,gross_sales,net_sales,stock_on_hand,stock_out_flag,lead_time_days,supplier_id,purchase_cost,margin_pct
0,2022-09-03,2022,9,3,35,5,1,0,15.42,1.26,...,0.0,0,310.88,310.88,337,0,7,S040,3.83,0.285
1,2022-09-04,2022,9,4,35,6,1,0,7.25,0.92,...,0.0,0,278.72,278.72,301,0,6,S022,2.92,0.455
2,2022-09-05,2022,9,5,36,0,0,0,11.77,0.06,...,0.0,0,176.88,176.88,286,0,7,S015,3.63,0.322
3,2022-09-06,2022,9,6,36,1,0,0,8.77,4.23,...,0.0,0,300.16,300.16,332,0,7,S001,3.98,0.258
4,2022-09-07,2022,9,7,36,2,0,0,11.01,1.46,...,0.0,0,321.60,321.60,448,0,5,S052,2.73,0.491

In [18]:
sample.columns.tolist()

['date',
 'year',
 'month',
 'day',
 'weekofyear',
 'weekday',
 'is_weekend',
 'is_holiday',
 'temperature',
 'rain_mm',
 'store_id',
 'country',
 'city',
 'channel',
 'latitude',
 'longitude',
 'sku_id',
 'sku_name',
 'category',
 'subcategory',
 'brand',
 'units_sold',
 'list_price',
 'discount_pct',
 'promo_flag',
 'gross_sales',
 'net_sales',
 'stock_on_hand',
 'stock_out_flag',
 'lead_time_days',
 'supplier_id',
 'purchase_cost',
 'margin_pct']

In [20]:
print(sample.columns.tolist())

['date', 'year', 'month', 'day', 'weekofyear', 'weekday', 'is_weekend', 'is_holiday', 'temperature', 'rain_mm', 'store_id', 'country', 'city', 'channel', 'latitude', 'longitude', 'sku_id', 'sku_name', 'category', 'subcategory', 'brand', 'units_sold', 'list_price', 'discount_pct', 'promo_flag', 'gross_sales', 'net_sales', 'stock_on_hand', 'stock_out_flag', 'lead_time_days', 'supplier_id', 'purchase_cost', 'margin_pct']

In [26]:
query = """
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_name = 'fmcg_sales'
ORDER BY ordinal_position;
"""

schema = pd.read_sql(query, engine)

schema

       column_name         data_type
0             date              date
1             year            bigint
2            month            bigint
3              day            bigint
4       weekofyear            bigint
5          weekday            bigint
6       is_weekend            bigint
7       is_holiday            bigint
8      temperature  double precision
9          rain_mm  double precision
10        store_id              text
11         country              text
12            city              text
13         channel              text
14        latitude  double precision
15       longitude  double precision
16          sku_id              text
17        sku_name              text
18        category              text
19     subcategory              text
20           brand              text
21      units_sold            bigint
22      list_price  double precision
23    discount_pct  double precision
24      promo_flag            bigint
25     gross_sales  double precision
26       net_sales  double precision
27   stock_on_hand            bigint
28  stock_out_flag            bigint
29  lead_time_days            bigint
30     supplier_id              text
31   purchase_cost  double precision
32      margin_pct  double precision

In [27]:
query = """
SELECT COUNT(DISTINCT sku_id) AS total_products
FROM fmcg_sales;
"""

pd.read_sql(query, engine)

   total_products
0             102

In [28]:
query = """
SELECT DISTINCT channel
FROM fmcg_sales
ORDER BY channel;
"""

pd.read_sql(query, engine)

       channel
0  Convenience
1   E-commerce
2  Hypermarket
3  Supermarket

In [29]:
query = """
SELECT
    sku_name,
    ROUND(AVG(list_price)::numeric,2) AS average_price
FROM fmcg_sales
GROUP BY sku_name
ORDER BY average_price DESC;
"""

pd.read_sql(query, engine)

             sku_name  average_price
0     BrandF Softener          14.80
1        BrandB Chips          14.57
2        BrandF Water          14.52
3    BrandE Detergent          14.47
4    BrandB Detergent          14.20
..                ...            ...
97      BrandC Yogurt           1.44
98      BrandB Yogurt           1.36
99        BrandF Soda           1.29
100     BrandE Cheese           1.10
101   BrandA Biscuits           1.08

[102 rows x 2 columns]

In [30]:
query = """
SELECT
    country,
    ROUND(SUM(net_sales)::numeric,2) AS revenue
FROM fmcg_sales
GROUP BY country
ORDER BY revenue DESC;
"""

pd.read_sql(query, engine)

       country       revenue
0        Italy  1.371931e+08
1        Spain  1.067048e+08
2      Germany  8.852556e+07
3      Austria  4.302003e+07
4       France  4.260161e+07
5       Poland  4.238526e+07
6  Netherlands  1.251615e+07

In [31]:
query = """
SELECT
    channel,
    ROUND(SUM(net_sales)::numeric,2) AS revenue
FROM fmcg_sales
GROUP BY channel
ORDER BY revenue DESC;
"""

pd.read_sql(query, engine)

       channel       revenue
0  Hypermarket  2.587381e+08
1   E-commerce  1.127345e+08
2  Supermarket  8.895766e+07
3  Convenience  1.251615e+07

In [32]:
query = """
SELECT
    sku_name,
    ROUND(AVG(units_sold)::numeric,2) AS avg_units
FROM fmcg_sales
GROUP BY sku_name
ORDER BY avg_units DESC;
"""

pd.read_sql(query, engine)

             sku_name  avg_units
0         BrandF Soda     126.50
1        BrandE Water     126.15
2         BrandA Soda     125.91
3    BrandE Chocolate     120.86
4        BrandC Chips     109.67
..                ...        ...
97    BrandC Biscuits      13.81
98    BrandF Biscuits      12.97
99       BrandC Water      11.76
100   BrandA Softener       9.56
101    BrandB Shampoo       8.93

[102 rows x 2 columns]

In [33]:
query = """
SELECT
    year,
    ROUND(SUM(net_sales)::numeric,2) AS total_sales
FROM fmcg_sales
GROUP BY year
ORDER BY year;
"""

pd.read_sql(query, engine)

   year   total_sales
0  2021  1.575602e+08
1  2022  1.578162e+08
2  2023  1.575701e+08

In [34]:
query = """
SELECT
    month,
    ROUND(SUM(net_sales)::numeric,2) AS total_sales
FROM fmcg_sales
GROUP BY month
ORDER BY month;
"""

pd.read_sql(query, engine)

    month  total_sales
0       1  39352968.55
1       2  35464637.38
2       3  38326971.40
3       4  37422055.01
4       5  38531533.74
5       6  40698129.92
6       7  42484351.18
7       8  42227144.51
8       9  37288053.60
9      10  38693965.46
10     11  40078420.89
11     12  42378221.19

In [35]:
query = """
SELECT
    is_weekend,
    ROUND(SUM(net_sales)::numeric,2) AS revenue
FROM fmcg_sales
GROUP BY is_weekend
ORDER BY is_weekend;
"""

pd.read_sql(query, engine)

   is_weekend       revenue
0           0  3.192653e+08
1           1  1.536811e+08

In [36]:
query = """
SELECT

sku_name,

SUM(net_sales) AS revenue,

RANK() OVER(

ORDER BY SUM(net_sales) DESC

) AS revenue_rank

FROM fmcg_sales

GROUP BY sku_name;
"""

ranking = pd.read_sql(query, engine)
ranking.head(20)

             sku_name      revenue  revenue_rank
0        BrandF Water  17032424.64             1
1        BrandC Chips  16000295.02             2
2        BrandB Chips  13025419.73             3
3   BrandC Toothpaste  12968809.43             4
4         BrandB Soap  12496995.90             5
5   BrandD Toothpaste  12351150.68             6
6       BrandD Cheese  12326994.00             7
7       BrandA Cheese  11967260.40             8
8        BrandD Chips  11749108.59             9
9   BrandA Toothpaste  11594508.71            10
10    BrandE Biscuits  10887379.87            11
11    BrandB Biscuits  10826032.60            12
12        BrandD Milk  10664140.20            13
13        BrandA Soda  10515682.83            14
14        BrandC Milk  10224239.22            15
15        BrandE Soda   9685683.36            16
16        BrandF Milk   9466848.00            17
17        BrandF Nuts   8917389.91            18
18        BrandB Soda   8625588.75            19
19        BrandC Nuts   8089038.53            20

In [37]:
query = """
SELECT

sku_name,

SUM(net_sales) revenue,

DENSE_RANK() OVER(

ORDER BY SUM(net_sales) DESC

) rank

FROM fmcg_sales

GROUP BY sku_name;
"""

dense_rank = pd.read_sql(query, engine)
dense_rank.head()

            sku_name      revenue  rank
0       BrandF Water  17032424.64     1
1       BrandC Chips  16000295.02     2
2       BrandB Chips  13025419.73     3
3  BrandC Toothpaste  12968809.43     4
4        BrandB Soap  12496995.90     5

In [38]:
query = """
SELECT

date,

SUM(net_sales) AS revenue,

SUM(SUM(net_sales)) OVER(

ORDER BY date

) AS cumulative_revenue

FROM fmcg_sales

GROUP BY date

ORDER BY date;
"""

running_sales = pd.read_sql(query, engine)
running_sales

            date    revenue  cumulative_revenue
0     2021-01-01  395308.15        3.953081e+05
1     2021-01-02  482497.08        8.778052e+05
2     2021-01-03  481362.59        1.359168e+06
3     2021-01-04  396538.69        1.755707e+06
4     2021-01-05  393292.28        2.148999e+06
...          ...        ...                 ...
1090  2023-12-27  440310.01        4.710332e+08
1091  2023-12-28  422565.95        4.714557e+08
1092  2023-12-29  449620.05        4.719054e+08
1093  2023-12-30  523906.46        4.724293e+08
1094  2023-12-31  517179.76        4.729465e+08

[1095 rows x 3 columns]

In [40]:
query = """
SELECT
    country,
    SUM(net_sales) AS revenue,
    ROUND(
        (
            100 * SUM(net_sales)
            / SUM(SUM(net_sales)) OVER ()
        )::numeric,
        2
    ) AS revenue_percent
FROM fmcg_sales
GROUP BY country
ORDER BY revenue_percent DESC;
"""

country_share = pd.read_sql(query, engine)
country_share

       country       revenue  revenue_percent
0        Italy  1.371931e+08            29.01
1        Spain  1.067048e+08            22.56
2      Germany  8.852556e+07            18.72
3      Austria  4.302003e+07             9.10
4       France  4.260161e+07             9.01
5       Poland  4.238526e+07             8.96
6  Netherlands  1.251615e+07             2.65